<?php
/**	op-core-tutorial:/Escape.phtml
 *
 * @created    2025-10-13
 * @license    Apache-2.0
 * @package    op-core
 * @subpackage tutorial
 * @copyright  (C) 2025 Tomoaki Nagahara
 */

/**	namespace
 *
 */
namespace OP;

?>
<section class="markdown" data-translation="true">
# What is Escape?

## Encode

```php
echo OP()->Encode('&lt;h1&gt;XSS');
```

## Decode

```php
echo OP()->Decode('&amp;lt;h1&amp;gt;XSS');
```
</section>
