<?php
/**	op-core-tutorial:/OP.php
 *
 * @created    2025-09-22
 * @version    1.0
 * @package    op-core
 * @subpackage tutorial
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

?>
<section class="markdown" data-translation="true">
# `OP()`

First, let’s explain `OP()`.
`OP()` is the core function of the ONEPIECE Framework.
It connects all the features of the ONEPIECE Framework, and by using `OP()`, you can access every function within the framework.
This time, we call `Request()`, which retrieves the URL query.

The first is the OP() function.
The `OP()` function is the core of the ONEPIECE Framework, enabling access to all of its.
</section>
