<?php
/**	op-core-tutorial:/Request.phtml
 *
 * @created    2025-09-22
 * @version    1.0
 * @package    op-core
 * @subpackage tutorial
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

?>

<section class="markdown" data-translation="true">
# `Request()`

`Request()` is a highly capable feature for retrieving URL queries.
First, it automatically escapes parameters, making it very secure against attacks such as XSS.
Next, it automatically switches between GET and POST.
Furthermore, it also automatically handles JSON.
</section>

<section class="markdown" data-translation="true">
# Key points of this chapter

In this chapter, we learned the basics of controlling pages.
By applying this basic, you can control any complex page.

You also learned about two important features:

And the other is the `Request()` function.
The `Request()` function is extremely useful for retrieving requests from users.
This is because it automatically escapes parameters, eliminating the risk of XSS.
In addition, it automatically switches between GET and POST, and not only that — it also supports JSON.
</section>
